### ISSUE TITLE
generation of PDF for sample/sample.ged is incorrect

### ISSUE THREAD

**Issue by baud123** [mrlem/genesys#6]
with v1.0.4 I still have a problem to generate the correct sample/sample.ged.pdf : 

```
$ genesys-1.0.4/bin/genesys
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
generating /home/baud/Development/genealogie/genesys/genesys-1.0.4/sample/sample.ged.pdf
content:
digraph G {
  node [shape=underline, fontsize=8, fontname=arial, margin=0.05, height=0, width=0];
  edge [dir=none, penwidth=0.5];
  peripheries=0
  "I1" [label="Robert Eugene
Williams"]
}

exec: dot -Tpdf /tmp/genesys_9085816660076136904.dot -o /home/baud/Development/genealogie/genesys/genesys-1.0.4/sample/sample.ged.pdf
exec: returned 0
```

and the PDF file shows only **one entry** though the GEDCOM file contains **many** entries.

BTW, _you_ have the same problem, as shown by your own generated PDF : 
https://github.com/mrlem/genesys/blob/v1.0.4/sample/sample.ged.pdf

I reproduce it in CLI with `genesys-1.0.4/bin/genesys genesys-1.0.4/sample/sample.ged -o genesys-1.0.4/sample/sample.ged_2.pdf`  (same with png & svg)

BTW, you may use /usr/share/doc/gramps/example/gedcom/sample.ged from the gramps project (same problem), you can get it at https://github.com/gramps-project/gramps/blob/master/example/gedcom/sample.ged

**Comment by mrlem** [comment]
Thanks for all the input, I made a simplification which worked for my own tree: in my case the root happened to be the first element... well it seems I'll have to get the root the clean way (I should probably also add a command-line parameter to specify a different root, by the way).

**Comment by baud123** [comment]
> I should probably also add a command-line parameter to specify a different root, by the way

yep identified by the INDI field (of the form Innnn) and displayed at the bottom of the execution with the last + first names recognized + number of individuals taken into account (for a quick verification).

**Comment by mrlem** [comment]
Version 1.0.5 just released, defaults to the most recent (by birth) individual, allows to set the root individual by name (firstnames lastname, or vice versa)

**Comment by mrlem** [comment]
As for the completeness in terms of individuals, I'll have to think.
The original purpose of the tool is to make a tree: to show all individuals would mean giving up this notion of root and display all individuals (maybe I should have a "mode" option which could be either "tree" or "full"?).
